### ISSUE TITLE
hey, how can i add a new parameter other than the current ones in catalog?

### ISSUE THREAD

**Issue by Yamac-Koc** [NoNameSpecified/UnbelievaBoat-Python-Bot#2]
hey @NoNameSpecified . I wonder how i can add another parameter to the item creation? i would appreciate it very much. Maybe do a tut about it. my discord is: **0lr.**
Thanks!

**Comment by NoNameSpecified** [comment]
fixed through discord, not added to repo cause too specific

**Comment by NoNameSpecified** [comment]
fixed through discord, not added to repo cause too specific
