### ISSUE TITLE
Roulette won't let bet on 0

### ISSUE THREAD

**Issue by alexpryan** [NoNameSpecified/UnbelievaBoat-Python-Bot#3]
The ball can still land on 0 but trying to bet on that space results in an error.

**Comment by NoNameSpecified** [comment]
ill look into it this evening, if you have discord you can dm me at kendrik2.0

**Comment by NoNameSpecified** [comment]
okay it should be fixed, was actually the same for 36. I just forgot to put greater/smaller than _or equal_ to lol.
If the problem persists however, you can open a new issue.
