### ISSUE TITLE
Error, help me please :(

### ISSUE THREAD

**Issue by TiagocCc** [NoNameSpecified/UnbelievaBoat-Python-Bot#4]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'database/database.json'
  File "C:\Users\pcprincipal\Downloads\UnbelievaBoat-Python-Bot-main\src\database\__init__.py", line 40, in __init__
    creating_file = open(self.pathToJson, "w")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pcprincipal\Downloads\UnbelievaBoat-Python-Bot-main\src\main.py", line 47, in <module>
    db_handler = database.pythonboat_database_handler(client)  # ("database.json")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'database/database.json'

**How can i solve it?**

**Comment by NoNameSpecified** [comment]
if you launch it through cmd and not powershell or an ide like pycharm, it might do that
try launching the script with powershell, tell me if the problem persists

**Comment by NoNameSpecified** [comment]
issue solved, was indeed a "/" problem with windows
other issue appeared, caused by an old discord.py version, "pip install --upgrade discord" fixed it.

issues fixed
