### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by 57tr** [NoNameSpecified/UnbelievaBoat-Python-Bot#7]
Update blackjack system pls

**Comment by 57tr** [comment]
Update blackjack system pls

**Comment by NoNameSpecified** [comment]
could you be more specific ? what exactly dyou mean

**Comment by 57tr** [comment]
> could you be more specific ? what exactly dyou mean

I want to say that if you could please update and review the blackjack system since I have been testing it and it does not work correctly. Thank you.

**Comment by NoNameSpecified** [comment]
Can you reach out on discord ? Add me at kendrik2.0, its easier to talk there, you can make a temporary account i think. Im gonna need more info to know what exactly needs to be fixed.

**Comment by 57tr** [comment]
There I sent you a request, my username is juan.cc02, when you accept me, talk to me and I'll tell you what happens with the code.
